/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as T3RouteImport } from './routes/t3'
import { Route as IndexRouteImport } from './routes/index'

const T3Route = T3RouteImport.update({
  id: '/t3',
  path: '/t3',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/t3': typeof T3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/t3': typeof T3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/t3': typeof T3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/t3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/t3'
  id: '__root__' | '/' | '/t3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  T3Route: typeof T3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/t3': {
      id: '/t3'
      path: '/t3'
      fullPath: '/t3'
      preLoaderRoute: typeof T3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  T3Route: T3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
